import Head from 'next/head';
import { motion as m } from 'framer-motion';
import { container, item } from '../animation';

export default function Contact() {
  return (
    <m.main
      // layout="position"
      initial={{ y: '100%' }}
      animate={{ y: '0' }}
      transition={{ duration: 0.75, ease: 'easeOut' }}
      // exit={{ opacity: 0 }}
      // style={{ overflow: 'scroll' }}
      className="text-gray-900 bg-red-400 p-10"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-60 p-1">
        <h1 className="text-6xl text-center lg:text-right lg:text-9xl">
          Say Hello!
        </h1>
      </div>
      <div className="flex gap-40">
        <div className="lg:text-2xl text-base">
          <h4>You need say hello</h4>
        </div>
        <div className="lg:text-6xl text-2xl underline">
          <m.ul variants={container} initial="hidden" animate="show">
            <div className="overflow-hidden">
              <m.li variants={item} className="pb-2">
                Twitter
              </m.li>
            </div>
            <div className="overflow-hidden">
              <m.li variants={item} className="pb-2">
                Instagram
              </m.li>
            </div>
            <div className="overflow-hidden">
              <m.li variants={item} className="pb-2">
                LinkedIn
              </m.li>
            </div>
            <div className="overflow-hidden">
              <m.li variants={item} className="pb-2">
                Telegram
              </m.li>
            </div>
          </m.ul>
        </div>
      </div>
    </m.main>
  );
}
