import Head from 'next/head';
import { motion as m } from 'framer-motion';

export default function Home() {
  return (
    <m.div
      // layout="position"
      initial={{ y: '100%' }}
      animate={{ y: '0' }}
      transition={{ duration: 0.75, ease: 'easeOut' }}
      // exit={{ opacity: 0 }}
      // style={{ overflow: 'scroll' }}
      className="text-gray-900  bg-orange-100 p-10"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="my-60 p-1">
          <m.h1
            animate={{ y: '0' }}
            initial={{ y: '100%' }}
            transition={{ delay: 0.5, duration: 1.5, ease: 'easeOut' }}
            className="text-6xl text-center lg:text-right lg:text-9xl"
          >
            Framer Motion Example
          </m.h1>
        </div>
        <div className="flex justify-between">
          <div>
            <h2>Point 1</h2>
            <h2>Description</h2>
            <h2>2022</h2>
          </div>
          <div>
            <h3>About of your company there</h3>
            <h3>This page used Framer motion plugin</h3>
            <h3>Next.js, React</h3>
          </div>
        </div>
      </main>
    </m.div>
  );
}
